"""Interventions and decisions — what the literature does not have.

I3 and PI-GN-JODE both predict cascades. Neither selects an intervention.
That gap is this module.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from contracts.criticality import Criticality, Damage

ActionKind = Literal["isolate", "harden", "reroute", "preposition", "shed"]


class Action(BaseModel):
    kind: ActionKind
    target: str = Field(description="Node.id or Edge.id")
    magnitude: float = Field(ge=0.0, le=1.0, description="kind-specific, normalised")
    cost: float = Field(ge=0.0, description="abstract units, from contracts/costs.json")
    lead_time_s: float = Field(ge=0.0, description="delay until it takes effect once ordered")


class Intervention(BaseModel):
    action: Action
    damage_prevented: Damage
    damage_prevented_headline: float
    benefit_per_cost: float
    p_success: float = Field(ge=0.0, le=1.0)
    deadline_s: float = Field(
        description=(
            "latest t at which ordering this still yields >= 90% of its current benefit. "
            "A prediction without a deadline is a weather forecast; with one it is an "
            "instruction."
        )
    )
    rationale: list[str] = Field(
        description=(
            "ordered, human-readable, generated BY TEMPLATE from rollout statistics. "
            "Never LLM-authored. A decision about which neighbourhood loses water has to "
            "be explainable line by line."
        )
    )
    n_rollouts: int = Field(ge=0)


class Decision(BaseModel):
    decision_id: str
    scenario_id: str
    t: float
    trigger: list[Criticality] = Field(description="what made us decide now")
    do_nothing_damage: Damage = Field(
        description=(
            "MANDATORY on every Decision. A recommendation without its counterfactual is "
            "a suggestion, and this project is about consequences."
        )
    )
    ranked: list[Intervention] = Field(description="descending benefit_per_cost; top 5")
    compute_ms: float
    seed: int
