"""Build the static site from the template plus the exported scenario.

Same source as the artifact. Numbers come from console/data/demo.json, which
is regenerated by scripts/export_demo.py — nothing here is typed by hand.
"""
from __future__ import annotations

import json
import pathlib
import re
import subprocess
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
TPL = ROOT / "scripts" / "pitch_template.html"
CONSOLE_TPL = ROOT / "scripts" / "console_template.html"
CONSOLE3D_TPL = ROOT / "scripts" / "console3d_template.html"
CONSOLE3D_APP = ROOT / "scripts" / "console3d_app.js"
DATA = ROOT / "console" / "data" / "demo.json"
RESULTS = ROOT / "eval" / "results"
OUT = ROOT / "www" / "index.html"
# The simulation lives at its own URL. It is an instrument, not a section of a
# write-up: full viewport, nothing scrolls, driven from the keyboard. Keeping it
# inside the pitch page meant the page had to be scrolled to during a demo.
# 3D is the console; 2D is the fallback that reads the identical scenario file.
# EXECUTION.md non-negotiable 6 requires the fallback to exist from day one, and
# the cut list puts "3D map (keep 2D)" above deployment — so both ship.
CONSOLE3D_OUT = ROOT / "www" / "sim" / "index.html"
CONSOLE_OUT = ROOT / "www" / "sim" / "2d" / "index.html"


def _res(name: str) -> dict:
    f = RESULTS / f"{name}.json"
    if not f.exists():
        raise SystemExit(f"missing {f}. Run the eval scripts before building the site — "
                         "no number on this page is allowed to be typed by hand.")
    return json.loads(f.read_text())


def _tag(kind: str, text: str) -> str:
    return f'<span class="tag {kind}">{text}</span>'


def _evidence_rows() -> str:
    """Every row here is read out of eval/results/*.json. None is typed.

    The page says "numbers regenerate from eval/, none typed by hand". It used
    to say that above a table of hand-typed constants, which had already gone
    stale against the results in the repo.
    """
    r, h, rec = _res("realism"), _res("h1"), _res("recovery")
    pl = r["powerlaw_test_REPORTED_NOT_GATING"]
    rows = [
        ("Realism gate — cascade sizes",
         f"span {r['span']:,.0f}\u00d7 \u00b7 tail {r['tail_sd']:.1f}\u03c3",
         ("pass", "Pass") if r["gate_checks"]["tail_heavy"] else ("fail", "Failed"),
         "Behaves like infrastructure"),
        ("Scenario contingency — is the outcome in play?",
         "all 5 hazards", ("pass", "Pass") if r["gate_checks"]["outcome_contingent"]
         else ("fail", "Failed"), "An intervention can still move it"),
        ("Power-law tail (we expected one)",
         f"LR {pl['lr_vs_exponential']:,.0f} \u00b7 p\u2248{pl['lr_p']:.0e}",
         ("pass", "Confirmed") if pl["powerlaw_favoured"] else ("fail", "Failed"),
         "Exponential wins. Subcritical."),
        ("Chain recovery — the thesis check",
         f"P {rec['precision']:.3f} \u00b7 R {rec['recall']:.3f}",
         ("pass", "Pass") if rec["f1"] > 0.7 else ("fail", "Failed"),
         "Near-misses <em>are</em> recoverable"),
        ("H1 — anomaly score is at chance",
         f"AUC {h['auc_anomaly_score']:.3f}",
         ("pass", "Confirmed") if 0.45 <= h["auc_anomaly_score"] <= 0.60 else ("fail", "Missed"),
         "As pre-registered"),
        ("H1 — ours \u2265 0.80",
         f"AUC {h['auc_branching_ratio']:.3f}",
         ("pass", "Pass") if h["auc_branching_ratio"] >= 0.80 else ("fail", "Short"),
         "Our target was optimistic"),
        ("Health-impact label",
         f"{h['label2_health_impact']['auc_anomaly_score']:.3f} \u2192 "
         f"{h['label2_health_impact']['auc_branching_ratio']:.3f}",
         ("part", f"+{h['label2_health_impact']['delta']:.3f}"),
         "The operational question"),
    ]
    return "\n".join(
        f"      <tr><td>{a}</td><td class=\"n\">{b}</td>"
        f"<td>{_tag(c[0], c[1])}</td><td>{d}</td></tr>"
        for a, b, c, d in rows)


def _auc_bars() -> str:
    h = _res("h1")
    bars = [("Anomaly score", "(what everyone builds)", h["auc_anomaly_score"], ""),
            ("Branching ratio", "(cascade label)", h["auc_branching_ratio"], " ours"),
            ("Branching ratio", "(health-impact label)",
             h["label2_health_impact"]["auc_branching_ratio"], " ours")]
    return "\n".join(
        f'    <div class="bar"><span>{n} <span style="color:var(--ink-3)">{sub}</span></span>'
        f'<span class="track"><span class="fill{cls}" style="width:{v*100:.1f}%"></span>'
        f'<span class="mid"></span></span><span class="val">{v:.3f}</span></div>'
        for n, sub, v, cls in bars)


def _arms() -> tuple[str, str]:
    """The arms table, led by the comparison that matters.

    `prevented` on its own is not a result: protecting five assets at random
    prevents damage too. The verdict column is the paired rank test against that
    baseline, and arms that do not clear it are shown as not clearing it.
    """
    a = _res("arms")
    cells = []
    for t in a["arms"]:
        if t["arm"] in ("A0", "AR"):
            verdict = "&mdash;"
        elif t.get("significant_vs_chance", t.get("beats_chance_95")):
            verdict = '<span class="tag pass">beats chance</span>'
        else:
            verdict = '<span class="tag fail">not vs chance</span>'
        cells.append(
            f"      <tr><td class=\"n\">{t['arm']}</td><td>{t['mechanism']}</td>"
            f"<td class=\"n\">{t['prevented']:,.0f}</td>"
            f"<td class=\"n\">{t['prevented_pct']:.1f}%</td>"
            f"<td class=\"n\">{t['vs_chance']:,.0f}</td>"
            f"<td>{verdict}</td>"
            f"<td class=\"n\">{t['oracle_captured_pct']:.0f}%</td></tr>")
    rows = "\n".join(cells)
    beat = [t["arm"] for t in a["arms"]
            if t.get("significant_vs_chance", t.get("beats_chance_95"))
            and t["arm"] not in ("A0", "AR")]
    cap = (f"{a['n_scenarios']} held-out scenarios, budget {a['budget']} interventions, one "
           "mechanism per arm. Interventions are applied in the engine and re-run on the same "
           "seed with paired randomness — a true counterfactual, not a score under our own "
           "rollout model. <b>Read the last two columns.</b> Arm <b>AR</b> protects five "
           "assets at random and prevents damage anyway, so &ldquo;prevented more than doing "
           "nothing&rdquo; is not the bar; the verdict is a Wilcoxon signed-rank test on the "
           "paired per-scenario difference against that baseline, Holm-corrected. "
           + (f"<b>Arms clearing it: {', '.join(beat)}.</b> " if beat
              else "<b>No arm clears it except the oracle.</b> ")
           + "<b>A5 &mdash; I\u00b3 (Tsinghua, arXiv 2503.02890) was not reproduced on our "
             "hardware; published numbers only, stated rather than quietly dropped.</b>")
    return rows, cap


def _count_tests() -> str:
    """Counted from the test files, not typed. It read 20 while 54 were green."""
    n = 0
    for f in (ROOT / "service" / "tests").glob("test_*.py"):
        n += len(re.findall(r"^def test_", f.read_text(), re.M))
    return str(n)


def _demo(d: dict) -> tuple[str, str]:
    runs, order = d.get("runs", {}), ["do_nothing", "firebreak", "human"]
    label = {"do_nothing": "Do nothing",
             "firebreak": "Firebreak\u2019s action",
             "human": "Harden the hospital (the human instinct)"}
    colour = {"do_nothing": "var(--alarm)", "firebreak": "var(--safe)",
              "human": "var(--accent)"}
    rows = []
    for k in order:
        if k not in runs:
            continue
        s = runs[k]["summary"]
        rows.append(
            f'<tr data-run="{k}"><td class="lab">'
            f'<span class="dot" style="background:{colour[k]}"></span>{label[k]}</td>'
            f'<td class="n">{s["assets_failed"]:,}</td>'
            f'<td class="n">{s["hospitals_hit"]}</td>'
            f'<td class="n">{s["person_hours"]:,.0f}</td></tr>')
    iv = d.get("intervention", {})
    caption = ""
    if runs and "firebreak" in runs and "human" in runs:
        fb, hu, dn = (runs["firebreak"]["summary"], runs["human"]["summary"],
                      runs["do_nothing"]["summary"])
        mins = int((iv.get("deadline_s") or 0) // 60)
        caption = (
            f"Same seed, same randomness, rewound twice. Firebreak\u2019s action "
            f"({iv.get('kind', 'n/a')} on {len(iv.get('targets', []))} assets, cost "
            f"{iv.get('cost', 0):.0f} units, deadline {mins} min) leaves "
            f"{fb['person_hours']:,.0f} person-hours lost against {dn['person_hours']:,.0f} "
            f"for doing nothing. Hardening the most critical asset instead \u2014 the same "
            f"budget, and what an experienced operator reaches for \u2014 leaves "
            f"{hu['person_hours']:,.0f}. <b>Beat 5 is supposed to fail, and CI asserts that "
            f"it does.</b> The decision took {iv.get('compute_ms', 0):,.0f} ms.")
    return "\n".join(rows), caption

CONSOLE_HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="description" content="Firebreak simulation console — replay a five-layer city cascade, rewind it, and compare what three different interventions do to the same seed.">
<meta name="color-scheme" content="light dark">
<meta name="robots" content="index,follow">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22><text y=%22.9em%22 font-size=%2258%22>&#128293;</text></svg>">
"""

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Firebreak — cascade prediction for interconnected city infrastructure. Catastrophes are too rare to learn from; near-misses are the same process stopped early.">
<meta name="color-scheme" content="light dark">
<meta property="og:title" content="Firebreak">
<meta property="og:description" content="Danger is not a property of an event. It is a property of its position in a network.">
<meta property="og:type" content="website">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22><text y=%22.9em%22 font-size=%2258%22>&#128293;</text></svg>">
<style>
  html{-webkit-text-size-adjust:100%}
  body{margin:0;font-size:14px}
  img{max-width:100%}
  [hidden]{display:none!important}
</style>
"""


def main() -> None:
    d = json.loads(DATA.read_text())
    for n in d["nodes"]:
        n["lat"] = round(n["lat"], 4)
        n["lon"] = round(n["lon"], 4)
    arms_rows, arms_caption = _arms()
    demo_rows, demo_caption = _demo(d)
    body = TPL.read_text()
    for key, val in (
        ("__DATA__", json.dumps(d, separators=(",", ":"))),
        ("__EVIDENCE_ROWS__", _evidence_rows()),
        ("__AUC_BARS__", _auc_bars()),
        ("__ARMS_ROWS__", arms_rows),
        ("__ARMS_CAPTION__", arms_caption),
        ("__DEMO_ROWS__", demo_rows),
        ("__DEMO_CAPTION__", demo_caption),
        ("__N_TESTS__", _count_tests()),
        ("__N_SCENARIOS__", f"{_res('realism')['n_scenarios']:,}"),
        ("__FLOOD_PEAK__", str((d.get("flood") or {}).get("peak", "n/a"))),
    ):
        body = body.replace(key, val)
    left = set(re.findall(r"__[A-Z_]+__", body))
    if left:
        raise SystemExit(f"unfilled placeholders in the template: {sorted(left)}")

    try:
        sha = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                      cwd=ROOT, text=True).strip()
    except Exception:
        sha = "dev"
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    body = body.replace("</footer>",
        f'  <span class="mono">build {sha} · {stamp}</span>\n</footer>')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEAD + "</head>\n<body>\n" + body + "\n</body>\n</html>\n")
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size:,} bytes)")

    # ---- the 3D console: the flood over Chennai ----
    payload = json.dumps(d, separators=(",", ":"))
    a, h1, h2, rec, rel = (_res("arms"), _res("h1"), _res("h2"),
                           _res("recovery"), _res("realism"))
    evidence = {
        "arms": a["arms"], "n_scenarios": a["n_scenarios"], "budget": a["budget"],
        "a5_note": a["A5_note"],
        "h1": {"anomaly": h1["auc_anomaly_score"], "branching": h1["auc_branching_ratio"],
               "centrality": h1["auc_static_betweenness"],
               "health_anomaly": h1["label2_health_impact"]["auc_anomaly_score"],
               "health_branching": h1["label2_health_impact"]["auc_branching_ratio"],
               "passed": h1["H1_PASSED"], "h4": h1["H4"]},
        "h2": {"learned": h2["rmse_learned"], "declared": h2["rmse_declared"],
               "rel": h2["relative_improvement"], "passed": h2["H2_PASSED"]},
        "recovery": {"precision": rec["precision"], "recall": rec["recall"], "f1": rec["f1"]},
        "realism": {"passed": rel["PASSED"], "span": rel["span"], "tail_sd": rel["tail_sd"],
                    "lr": rel["powerlaw_test_REPORTED_NOT_GATING"]["lr_vs_exponential"],
                    "powerlaw": rel["powerlaw_test_REPORTED_NOT_GATING"]["powerlaw_favoured"],
                    "contingency": rel["scenario_contingency"]},
    }
    c3 = (CONSOLE3D_TPL.read_text()
          .replace("__DATA__", payload)
          .replace("__EVIDENCE__", json.dumps(evidence, separators=(",", ":"))))
    left = set(re.findall(r"__[A-Z_]+__", c3))
    if left:
        raise SystemExit(f"unfilled placeholders in the 3D template: {sorted(left)}")
    CONSOLE3D_OUT.parent.mkdir(parents=True, exist_ok=True)
    CONSOLE3D_OUT.write_text(
        CONSOLE_HEAD + "</head>\n<body>\n" + c3 + "\n</body>\n</html>\n")
    (CONSOLE3D_OUT.parent / "app.js").write_text(CONSOLE3D_APP.read_text())
    print(f"wrote {CONSOLE3D_OUT.relative_to(ROOT)}  ({CONSOLE3D_OUT.stat().st_size:,} bytes)")

    # ---- the 2D fallback, same data, no WebGL and no tiles ----
    console = CONSOLE_TPL.read_text().replace("__DATA__", payload)
    left = set(re.findall(r"__[A-Z_]+__", console))
    if left:
        raise SystemExit(f"unfilled placeholders in the console template: {sorted(left)}")
    CONSOLE_OUT.parent.mkdir(parents=True, exist_ok=True)
    CONSOLE_OUT.write_text(
        CONSOLE_HEAD + "</head>\n<body>\n" + console + "\n</body>\n</html>\n")
    print(f"wrote {CONSOLE_OUT.relative_to(ROOT)}  ({CONSOLE_OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
