"""Build the static site from the template plus the exported scenario.

Same source as the artifact. Numbers come from console/data/demo.json, which
is regenerated by scripts/export_demo.py — nothing here is typed by hand.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
TPL = ROOT / "scripts" / "pitch_template.html"
DATA = ROOT / "console" / "data" / "demo.json"
OUT = ROOT / "site" / "index.html"

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Firebreak — cascade prediction for interconnected city infrastructure. Catastrophes are too rare to learn from; near-misses are the same process stopped early.">
<meta name="color-scheme" content="light dark">
<meta property="og:title" content="Firebreak">
<meta property="og:description" content="Danger is not a property of an event. It is a property of its position in a network.">
<meta property="og:type" content="website">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22><text y=%22.9em%22 font-size=%2258%22>&#128293;</text></svg>">
<style>
  html{-webkit-text-size-adjust:100%}
  body{margin:0;font-size:14px}
  img{max-width:100%}
  [hidden]{display:none!important}
</style>
"""


def main() -> None:
    d = json.loads(DATA.read_text())
    for n in d["nodes"]:
        n["lat"] = round(n["lat"], 4)
        n["lon"] = round(n["lon"], 4)
        n.pop("buf", None)
    body = TPL.read_text().replace("__DATA__", json.dumps(d, separators=(",", ":")))

    try:
        sha = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                      cwd=ROOT, text=True).strip()
    except Exception:
        sha = "dev"
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    body = body.replace("</footer>",
        f'  <span class="mono">build {sha} · {stamp}</span>\n</footer>')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEAD + "</head>\n<body>\n" + body + "\n</body>\n</html>\n")
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
